<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $projects = array(
                array('id' => '4','category_id' => '75','title' => 'Mobile App Design','slug' => 'mobile-app-design','release_at' => '2024-02-27','preview' => '/demo/WxFu1tRVY1b6qA75jGrf.jpg','banner_preview' => '/demo/RiAYjU6uMlhZJGUeHjSk.jpg','description' => 'Dive Deeper, Discover Brilliance: Explore Project Insights!','overview' => '<h4>Duis aute irure dolor in reprehenderit</h4><p>Posuere nibh vestibulum, velit pulvinar interdum sed in. Magnis netus magna urna, in tempor magna. Tortor vel vitae vel mi. Leo pellentesque eget pellentesque magnis. Pellentesque molestie sem massa nibh suspendisse ante eget. Sit dolor arcu scelerisque sit nibh nunc, vulputate cursus. Feugiat in tortor non mauris, sit. Hac adipiscing dui sit magna. Integer elementum et amet hac turpis. Sagittis magna nulla ut gravida integer pellentesque.</p><p>&nbsp;</p><h4>Overview</h4><ul><li>Create &amp; Save your notes with multi-media</li><li>Complete note editor with rich text options</li><li>Automatically sync in real time</li><li>Web Clipper Extension</li></ul><p>&nbsp;</p><p>Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a.</p>','output' => 'Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a. In gravida velit pretium commodo odio ridiculus odio enim.Tincidunt eget tellus pellentesque nulla.
                                  
                                  Sed morbi dignissim odio enim volutpat. Viverra facilisi aliquet sed purus id ornare nunc, sit ipsum.Risus amet non eget velit nunc, libero','client' => 'Microsoft App Holing Ltd, Australia Area','preview_link' => '/contact-us','is_active' => '1','is_featured' => '1','meta' => '{"title":"Mobile App Design","image":null,"description":"Mobile App Design Description","tags":"Mobile, App, Design"}','created_at' => '2023-11-23 10:13:53','updated_at' => '2024-04-30 08:35:44'),
                array('id' => '5','category_id' => '67','title' => 'Airbnb Upgrade','slug' => 'airbnb-upgrade','release_at' => '2024-03-05','preview' => '/demo/o2YZ9VcKEL97rpZ7nm3e.jpg','banner_preview' => '/demo/rfbl8EofA3Lt4KlqB9jc.jpg','description' => 'Dive Deeper, Discover Brilliance: Explore Project Insights!','overview' => '<h4><strong>Overview</strong></h4><ul><li>Create &amp; Save your notes with multi-media</li><li>Complete note editor with rich text options</li><li>Automatically sync in real time</li><li>Web Clipper Extension</li></ul><p>Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a.</p>','output' => 'Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a. In gravida velit pretium commodo odio ridiculus odio enim.Tincidunt eget tellus pellentesque nulla.
                                  
                      Sed morbi dignissim odio enim volutpat. Viverra facilisi aliquet sed purus id ornare nunc, sit ipsum.Risus amet non eget','client' => 'DESIGN WOK, BRANDING','preview_link' => '/contact-us','is_active' => '1','is_featured' => '1','meta' => '{"title":"Airbnb Upgrade","image":null,"description":null,"tags":null}','created_at' => '2024-04-01 11:17:01','updated_at' => '2024-04-30 08:35:59'),
                array('id' => '6','category_id' => '68','title' => 'Branding & Identity','slug' => 'branding-identity','release_at' => '2024-02-20','preview' => '/demo/Mca4eXBtS6wj7qFxbSZW.jpg','banner_preview' => '/demo/0SYVJ2yCiKziaitB1slZ.jpg','description' => 'Dive Deeper, Discover Brilliance: Explore Project Insights!','overview' => '<h4><strong>Overview</strong></h4><ul><li>Create &amp; Save your notes with multi-media</li><li>Complete note editor with rich text options</li><li>Automatically sync in real time</li><li>Web Clipper Extension</li></ul><p>Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a.</p><p><img src="assets/img/project/solution-1.jpg" alt=""></p><p><img src="assets/img/project/solution-2.jpg" alt=""></p>','output' => 'Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a. In gravida velit pretium commodo odio ridiculus odio enim.Tincidunt eget tellus pellentesque nulla.
                                  
                                  Sed morbi dignissim odio enim volutpat. Viverra facilisi aliquet sed purus id ornare nunc, sit ipsum.Risus amet non eget','client' => 'Microsoft App Holing Ltd, Australia Area','preview_link' => '/contact-us','is_active' => '1','is_featured' => '1','meta' => '{"title":"Branding & Identity","image":null,"description":null,"tags":null}','created_at' => '2024-04-01 11:19:22','updated_at' => '2024-04-30 08:36:21'),
                array('id' => '7','category_id' => '65','title' => 'Muckup Design','slug' => 'muckup-design','release_at' => '2023-09-19','preview' => '/demo/P97DdeqMpdYFWGboD5f0.jpg','banner_preview' => '/demo/pUZGm5JlZdfyns4H4Sof.jpg','description' => 'Dive Deeper, Discover Brilliance: Explore Project Insights!','overview' => '<h4>Duis aute irure dolor in reprehenderit</h4><p>Posuere nibh vestibulum, velit pulvinar interdum sed in. Magnis netus magna urna, in tempor magna. Tortor vel vitae vel mi. Leo pellentesque eget pellentesque magnis. Pellentesque molestie sem massa nibh suspendisse ante eget. Sit dolor arcu scelerisque sit nibh nunc, vulputate cursus. Feugiat in tortor non mauris, sit. Hac adipiscing dui sit magna. Integer elementum et amet hac turpis. Sagittis magna nulla ut gravida integer pellentesque.</p><p>&nbsp;</p><h4>Overview</h4><ul><li>Create &amp; Save your notes with multi-media</li><li>Complete note editor with rich text options</li><li>Automatically sync in real time</li><li>Web Clipper Extension</li></ul><p>&nbsp;</p><p>Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a.</p>','output' => 'Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a. In gravida velit pretium commodo odio ridiculus odio enim.Tincidunt eget tellus pellentesque nulla.
                                  
                                  Sed morbi dignissim odio enim volutpat. Viverra facilisi aliquet sed purus id ornare nunc, sit ipsum.Risus amet non eget','client' => 'Microsoft App Holing Ltd, Australia Area','preview_link' => '/contact-us','is_active' => '1','is_featured' => '0','meta' => '{"title":"Muckup Design","image":null,"description":null,"tags":null}','created_at' => '2024-04-01 21:10:30','updated_at' => '2024-04-30 08:36:35'),
                array('id' => '8','category_id' => '74','title' => 'Realistic Scenarios','slug' => 'realistic-scenarios','release_at' => '2023-07-11','preview' => '/demo/YV3tRXEO2mR5NnIfFXQU.jpg','banner_preview' => '/demo/78T4RRozWrchaabue3G8.png','description' => 'Dive Deeper, Discover Brilliance: Explore Project Insights!','overview' => '<h4>Duis aute irure dolor in reprehenderit</h4><p>Posuere nibh vestibulum, velit pulvinar interdum sed in. Magnis netus magna urna, in tempor magna. Tortor vel vitae vel mi. Leo pellentesque eget pellentesque magnis. Pellentesque molestie sem massa nibh suspendisse ante eget. Sit dolor arcu scelerisque sit nibh nunc, vulputate cursus. Feugiat in tortor non mauris, sit. Hac adipiscing dui sit magna. Integer elementum et amet hac turpis. Sagittis magna nulla ut gravida integer pellentesque.</p><p>&nbsp;</p><h4>Overview</h4><ul><li>Create &amp; Save your notes with multi-media</li><li>Complete note editor with rich text options</li><li>Automatically sync in real time</li><li>Web Clipper Extension</li></ul><p>&nbsp;</p><p>Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a.</p>','output' => 'Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a. In gravida velit pretium commodo odio ridiculus odio enim.Tincidunt eget tellus pellentesque nulla.
                                  
                                  Sed morbi dignissim odio enim volutpat. Viverra facilisi aliquet sed purus id ornare nunc, sit ipsum.Risus amet non eget','client' => 'Microsoft App Holing Ltd, Australia Area','preview_link' => '/contact-us','is_active' => '1','is_featured' => '1','meta' => '{"title":"Realistic Scenarios","image":null,"description":null,"tags":null}','created_at' => '2024-04-01 21:12:28','updated_at' => '2024-04-30 08:36:44'),
                array('id' => '9','category_id' => '65','title' => 'Web Design','slug' => 'web-design','release_at' => '2022-11-30','preview' => '/demo/1AjKGqkSWT4RfC6YWTXw.jpg','banner_preview' => '/demo/Ho7aspqxAi5NyC9KiA0k.jpg','description' => 'Dive Deeper, Discover Brilliance: Explore Project Insights!','overview' => '<h4>Duis aute irure dolor in reprehenderit</h4><p>Posuere nibh vestibulum, velit pulvinar interdum sed in. Magnis netus magna urna, in tempor magna. Tortor vel vitae vel mi. Leo pellentesque eget pellentesque magnis. Pellentesque molestie sem massa nibh suspendisse ante eget. Sit dolor arcu scelerisque sit nibh nunc, vulputate cursus. Feugiat in tortor non mauris, sit. Hac adipiscing dui sit magna. Integer elementum et amet hac turpis. Sagittis magna nulla ut gravida integer pellentesque.</p><p>&nbsp;</p><h4>Overview</h4><ul><li>Create &amp; Save your notes with multi-media</li><li>Complete note editor with rich text options</li><li>Automatically sync in real time</li><li>Web Clipper Extension</li></ul><p>&nbsp;</p><p>Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a.</p>','output' => 'Felis morbi ut tristique pretium libero. Eget purus, enim, orci, quis tempor sed. Sed nec eget nibh et Ut orci, sagittis tellus dui congue. Blandit laoreet nullam amet eget. Ut tincidunt diam tempor sed turpis odio vitae sem lobortis. Lobortis enim non eu a. In gravida velit pretium commodo odio ridiculus odio enim.Tincidunt eget tellus pellentesque nulla.
                                  
                                  Sed morbi dignissim odio enim volutpat. Viverra facilisi aliquet sed purus id ornare nunc, sit ipsum.Risus amet non eget','client' => 'Microsoft App Holing Ltd, Australia Area','preview_link' => '/contact-us','is_active' => '1','is_featured' => '1','meta' => '{"title":"Web Design","image":null,"description":null,"tags":null}','created_at' => '2024-04-01 21:13:56','updated_at' => '2024-04-30 08:37:10')
              );
  
        Project::insert($projects);
    }
}
